#!/usr/bin/env python3
"""Generate weak 2D floorplan ground truth from ScanNet semantic meshes.

The output is a top-down structural reference generated by projecting selected
semantic mesh vertices, such as wall/door/window, to the XY plane. It is useful
for evaluating density-map quality, but it is not a CAD-grade floorplan label.
"""

from __future__ import annotations

import argparse
import json
import struct
from pathlib import Path
from typing import Any

import cv2
import numpy as np
from PIL import Image, ImageDraw


PLY_TYPES = {
    "char": ("i1", 1),
    "int8": ("i1", 1),
    "uchar": ("u1", 1),
    "uint8": ("u1", 1),
    "short": ("i2", 2),
    "int16": ("i2", 2),
    "ushort": ("u2", 2),
    "uint16": ("u2", 2),
    "int": ("i4", 4),
    "int32": ("i4", 4),
    "uint": ("u4", 4),
    "uint32": ("u4", 4),
    "float": ("f4", 4),
    "float32": ("f4", 4),
    "double": ("f8", 8),
    "float64": ("f8", 8),
}

DEFAULT_STRUCTURE_LABELS = {
    1: "wall",
    8: "door",
    9: "window",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    input_group = parser.add_mutually_exclusive_group(required=True)
    input_group.add_argument("--semantic-mesh", type=Path)
    input_group.add_argument("--scan-root", type=Path)
    parser.add_argument("--scene-id", type=str, default=None)
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument(
        "--labels",
        type=str,
        default="1,8,9",
        help="Comma-separated NYU40 ids to project. Defaults: wall,door,window.",
    )
    parser.add_argument("--grid-size", type=int, default=512)
    parser.add_argument("--bounds-low-percentile", type=float, default=1.0)
    parser.add_argument("--bounds-high-percentile", type=float, default=99.0)
    parser.add_argument("--bounds-margin", type=float, default=0.05)
    parser.add_argument("--min-component-area", type=int, default=80)
    parser.add_argument("--close-kernel", type=int, default=5)
    parser.add_argument("--dilate-kernel", type=int, default=3)
    parser.add_argument("--dilate-iterations", type=int, default=1)
    parser.add_argument("--edge-method", choices=["canny", "morph"], default="canny")
    parser.add_argument("--canny-low", type=int, default=50)
    parser.add_argument("--canny-high", type=int, default=150)
    parser.add_argument("--max-scenes", type=int, default=None)
    return parser.parse_args()


def parse_label_ids(value: str) -> set[int]:
    labels = set()
    for part in value.split(","):
        part = part.strip()
        if part:
            labels.add(int(part))
    if not labels:
        raise ValueError("At least one semantic label id is required")
    return labels


def read_ply_header(path: Path) -> tuple[str, int, list[tuple[str, str]], int]:
    with path.open("rb") as f:
        first = f.readline().decode("ascii", errors="replace").strip()
        if first != "ply":
            raise ValueError(f"{path} is not a PLY file")

        fmt = None
        vertex_count = None
        vertex_properties: list[tuple[str, str]] = []
        current_element = None
        while True:
            line_bytes = f.readline()
            if not line_bytes:
                raise ValueError(f"{path} ended before end_header")
            line = line_bytes.decode("ascii", errors="replace").strip()
            if line == "end_header":
                return fmt or "", int(vertex_count or 0), vertex_properties, f.tell()
            if not line or line.startswith("comment"):
                continue
            parts = line.split()
            if parts[0] == "format":
                fmt = parts[1]
            elif parts[0] == "element":
                current_element = parts[1]
                if current_element == "vertex":
                    vertex_count = int(parts[2])
            elif parts[0] == "property" and current_element == "vertex":
                if parts[1] == "list":
                    raise ValueError("List properties are not expected in the vertex element")
                vertex_properties.append((parts[2], parts[1]))


def load_vertex_table(path: Path) -> dict[str, np.ndarray]:
    fmt, vertex_count, properties, data_offset = read_ply_header(path)
    if vertex_count <= 0:
        raise ValueError(f"No vertices found in {path}")

    if fmt == "ascii":
        names = [name for name, _ in properties]
        data = np.loadtxt(path, skiprows=_count_header_lines(path), max_rows=vertex_count)
        if data.ndim == 1:
            data = data[None, :]
        return {name: data[:, idx] for idx, name in enumerate(names)}

    if fmt not in {"binary_little_endian", "binary_big_endian"}:
        raise ValueError(f"Unsupported PLY format: {fmt}")

    endian = "<" if fmt == "binary_little_endian" else ">"
    dtype_fields = []
    for name, ply_type in properties:
        if ply_type not in PLY_TYPES:
            raise ValueError(f"Unsupported PLY property type: {ply_type}")
        numpy_code, _ = PLY_TYPES[ply_type]
        dtype_fields.append((name, endian + numpy_code))
    dtype = np.dtype(dtype_fields)
    with path.open("rb") as f:
        f.seek(data_offset)
        table = np.fromfile(f, dtype=dtype, count=vertex_count)
    return {name: table[name] for name, _ in properties}


def _count_header_lines(path: Path) -> int:
    count = 0
    with path.open("rb") as f:
        for line in f:
            count += 1
            if line.strip() == b"end_header":
                return count
    raise ValueError(f"{path} ended before end_header")


def find_semantic_meshes(args: argparse.Namespace) -> list[Path]:
    if args.semantic_mesh:
        return [args.semantic_mesh]

    root = args.scan_root
    if args.scene_id:
        candidates = [
            root / args.scene_id / f"{args.scene_id}_vh_clean_2.labels.ply",
            root / f"{args.scene_id}_vh_clean_2.labels.ply",
        ]
        for path in candidates:
            if path.exists():
                return [path]
        raise FileNotFoundError(f"Could not find labels PLY for scene {args.scene_id} under {root}")

    meshes = sorted(root.glob("scene*/*_vh_clean_2.labels.ply"))
    if not meshes:
        meshes = sorted(root.glob("*_vh_clean_2.labels.ply"))
    if args.max_scenes is not None:
        meshes = meshes[: args.max_scenes]
    if not meshes:
        raise FileNotFoundError(f"No *_vh_clean_2.labels.ply files found under {root}")
    return meshes


def normalize_counts(counts: np.ndarray) -> np.ndarray:
    density = np.log1p(counts.astype(np.float32))
    positive = density[density > 0]
    if positive.size == 0:
        return density
    scale = np.percentile(positive, 99)
    return np.clip(density / max(float(scale), 1e-8), 0.0, 1.0)


def save_gray(path: Path, image: np.ndarray) -> None:
    Image.fromarray(np.clip(image, 0, 255).astype(np.uint8)).save(path)


def density_to_visual(density: np.ndarray) -> np.ndarray:
    return (255.0 * (1.0 - np.sqrt(np.clip(density, 0.0, 1.0)))).astype(np.uint8)


def remove_small_components(mask: np.ndarray, min_area: int) -> np.ndarray:
    if min_area <= 0:
        return mask
    count, labels, stats, _ = cv2.connectedComponentsWithStats(mask.astype(np.uint8), 8)
    filtered = np.zeros(mask.shape, dtype=np.uint8)
    for label_id in range(1, count):
        if stats[label_id, cv2.CC_STAT_AREA] >= min_area:
            filtered[labels == label_id] = 1
    return filtered.astype(bool)


def rasterize_xy(
    xy: np.ndarray,
    grid_size: int,
    low_percentile: float,
    high_percentile: float,
    margin_ratio: float,
) -> tuple[np.ndarray, dict[str, Any]]:
    lower = np.percentile(xy, low_percentile, axis=0)
    upper = np.percentile(xy, high_percentile, axis=0)
    margin = (upper - lower) * margin_ratio
    lower -= margin
    upper += margin
    scale = (grid_size - 1) / np.maximum(upper - lower, 1e-8)
    coords = ((xy - lower) * scale).astype(np.int32)
    valid = np.logical_and(coords >= 0, coords < grid_size).all(axis=1)
    coords = coords[valid]
    counts = np.zeros((grid_size, grid_size), dtype=np.uint32)
    np.add.at(counts, (grid_size - 1 - coords[:, 1], coords[:, 0]), 1)
    return counts, {
        "xy_bounds": [lower.tolist(), upper.tolist()],
        "valid_projected_points": int(valid.sum()),
    }


def make_masks(counts: np.ndarray, args: argparse.Namespace) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    density = normalize_counts(counts)
    mask = counts > 0
    if args.close_kernel > 1:
        kernel = np.ones((args.close_kernel, args.close_kernel), dtype=np.uint8)
        mask = cv2.morphologyEx(mask.astype(np.uint8), cv2.MORPH_CLOSE, kernel).astype(bool)
    mask = remove_small_components(mask, args.min_component_area)
    if args.dilate_kernel > 1 and args.dilate_iterations > 0:
        kernel = np.ones((args.dilate_kernel, args.dilate_kernel), dtype=np.uint8)
        mask = cv2.dilate(mask.astype(np.uint8), kernel, iterations=args.dilate_iterations).astype(bool)

    mask_u8 = (mask.astype(np.uint8) * 255)
    if args.edge_method == "canny":
        line = cv2.Canny(mask_u8, args.canny_low, args.canny_high) > 0
    else:
        kernel = np.ones((3, 3), dtype=np.uint8)
        eroded = cv2.erode(mask_u8, kernel, iterations=1)
        line = (mask_u8 - eroded) > 0
    return density, mask, line


def save_diagnostics(
    output_path: Path,
    density: np.ndarray,
    mask: np.ndarray,
    line: np.ndarray,
    title: str,
) -> None:
    panels = [
        ("density", density_to_visual(density)),
        ("binary mask", 255 - mask.astype(np.uint8) * 255),
        ("line gt", 255 - line.astype(np.uint8) * 255),
    ]
    cell = 256
    label_h = 28
    canvas = Image.new("RGB", (cell * len(panels), cell + label_h), "white")
    draw = ImageDraw.Draw(canvas)
    for idx, (label, image) in enumerate(panels):
        x = idx * cell
        canvas.paste(Image.fromarray(image).convert("RGB").resize((cell, cell)), (x, label_h))
        draw.text((x + 6, 6), f"{title} {label}", fill=(0, 0, 0))
    canvas.save(output_path)


def process_mesh(path: Path, output_root: Path, label_ids: set[int], args: argparse.Namespace) -> dict[str, Any]:
    table = load_vertex_table(path)
    required = {"x", "y", "z"}
    missing = required.difference(table)
    if missing:
        raise ValueError(f"{path} missing vertex properties: {sorted(missing)}")
    label_key = None
    for candidate in ("label", "semantic_label", "nyu40id", "nyu40"):
        if candidate in table:
            label_key = candidate
            break
    if label_key is None:
        raise ValueError(
            f"{path} has no semantic label property. Expected one of: label, semantic_label, nyu40id, nyu40"
        )

    labels = np.asarray(table[label_key]).astype(np.int32)
    points = np.stack([table["x"], table["y"], table["z"]], axis=1).astype(np.float32)
    valid = np.isfinite(points).all(axis=1) & np.isin(labels, list(label_ids))
    selected = points[valid]
    selected_labels = labels[valid]
    if len(selected) == 0:
        raise ValueError(f"No selected semantic vertices in {path}; labels={sorted(label_ids)}")

    scene_id = path.name.replace("_vh_clean_2.labels.ply", "")
    output_dir = output_root / scene_id
    output_dir.mkdir(parents=True, exist_ok=True)

    counts, projection_meta = rasterize_xy(
        selected[:, :2],
        args.grid_size,
        args.bounds_low_percentile,
        args.bounds_high_percentile,
        args.bounds_margin,
    )
    density, mask, line = make_masks(counts, args)

    np.save(output_dir / "structure_counts.npy", counts)
    np.save(output_dir / "structure_density.npy", density.astype(np.float32))
    np.save(output_dir / "structure_mask.npy", mask.astype(np.uint8))
    np.save(output_dir / "structure_line_gt.npy", line.astype(np.uint8))
    save_gray(output_dir / "structure_density.png", density_to_visual(density))
    save_gray(output_dir / "structure_mask.png", 255 - mask.astype(np.uint8) * 255)
    save_gray(output_dir / "structure_line_gt.png", 255 - line.astype(np.uint8) * 255)
    save_diagnostics(output_dir / "structure_gt_diagnostics.png", density, mask, line, scene_id)

    label_hist = {
        int(label): int((selected_labels == label).sum())
        for label in sorted(np.unique(selected_labels))
    }
    metadata = {
        "scene_id": scene_id,
        "source_mesh": str(path),
        "label_property": label_key,
        "selected_labels": {
            str(label): DEFAULT_STRUCTURE_LABELS.get(label, "custom")
            for label in sorted(label_ids)
        },
        "selected_vertex_count": int(len(selected)),
        "label_histogram": label_hist,
        "grid_size": int(args.grid_size),
        "projection": projection_meta,
        "nonzero_density_pixels": int((counts > 0).sum()),
        "mask_pixels": int(mask.sum()),
        "line_pixels": int(line.sum()),
        "note": (
            "This is a ScanNet semantic-mesh projection reference, suitable as weak "
            "2D structural GT for density evaluation rather than CAD-level floorplan GT."
        ),
        "outputs": {
            "density": "structure_density.png",
            "mask": "structure_mask.png",
            "line": "structure_line_gt.png",
            "diagnostics": "structure_gt_diagnostics.png",
        },
    }
    with (output_dir / "structure_gt_info.json").open("w", encoding="utf-8") as f:
        json.dump(metadata, f, ensure_ascii=False, indent=2)
    return metadata


def main() -> None:
    args = parse_args()
    label_ids = parse_label_ids(args.labels)
    meshes = find_semantic_meshes(args)
    args.output_dir.mkdir(parents=True, exist_ok=True)

    summaries = []
    for mesh in meshes:
        print(f"Processing {mesh}")
        try:
            metadata = process_mesh(mesh, args.output_dir, label_ids, args)
            summaries.append(metadata)
            print(
                f"  saved {metadata['scene_id']}: vertices={metadata['selected_vertex_count']}, "
                f"line_pixels={metadata['line_pixels']}"
            )
        except Exception as exc:
            print(f"  failed {mesh}: {exc}")
            summaries.append({"source_mesh": str(mesh), "error": str(exc)})

    with (args.output_dir / "scannet_structure_gt_summary.json").open("w", encoding="utf-8") as f:
        json.dump(summaries, f, ensure_ascii=False, indent=2)
    print(f"Saved summary to {args.output_dir / 'scannet_structure_gt_summary.json'}")


if __name__ == "__main__":
    main()
